apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis01
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity: 
    storage: 1Gi
  hostPath:
    path: "/redis01"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis02
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity: 
    storage: 1Gi
  hostPath:
    path: "/redis02"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis03
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity: 
    storage: 1Gi
  hostPath:
    path: "/redis03"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis04
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity: 
    storage: 1Gi
  hostPath:
    path: "/redis04"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis05
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity: 
    storage: 1Gi
  hostPath:
    path: "/redis05"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis06
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity: 
    storage: 1Gi
  hostPath:
    path: "/redis06"
