apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster

spec:
  selector:
    matchLabels:
      name: redis-sts
  replicas: 6
  serviceName: redis-cluster-service
  template:
    metadata:
      labels:
        name: redis-sts

    spec:
      containers:
        - name: redis-sts-cont
          image: redis:5.0.1-alpine
          command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
          env:
            - name: POD_IP
              valueFrom:
                  fieldRef:
                    fieldPath: 'status.podIP'
          ports:
            - name: client
              containerPort: 6379
            - name: gossip
              containerPort: 16379
          volumeMounts:
            - name: conf
              mountPath: "/conf"
              readOnly: false
              # defaultMode: 0755
            - name: data
              mountPath: "/data"
              readOnly: false
      volumes:
      - name: conf
        # type: ConfigMap
        configMap:
            name: 'redis-cluster-configmap'
            defaultMode: 0755
  volumeClaimTemplates: 
  - metadata:
      name: data 
    spec:
      accessModes: [ 'ReadWriteOnce' ]
      storageClassName: manual
      resources:
        requests:
          storage: 1Gi