apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  type: NodePort
  selector:
    name: gop-fileserver
  ports:
  - port: 8080
    targetPort: 8080

#Aksios Podo, ilon misas! Kesrio syt logis zobrie issa se ossyngnoti errars

