apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
spec:
  type: ClusterIP
  selector:
    app: drupal-mysql
  ports:
  - port: 3306
    targetPort: 3306


#Nyk skan jiva schedulara! Zer poda! Zer poda! Zer poda!
